### ISSUE TITLE
Escaping characters with backslash will include the backslash in the output

### ISSUE THREAD

**Issue by keshav-pudaruth-daytonatec** [aurimasniekis/idea-php-class-templates#2]
PHPstorm version: 2018.2
Environment: Windows 10 Pro 64-bit

**Example of file template:**

```php

<?php
class ${NAME} {
    public $myProperty;
}
```

Apache velocity will pick up the `$myProperty` as a template variable.
Therefore, the variable is escaped using a backslash in the template:

```php

<?php
class ${NAME} {
    public \$myProperty;
}
```

**Expected File Output:**

```php

<?php
class myClass {
    public $myProperty;
}
```

**Actual File Output:**

```php

<?php
class myClass {
    public \$myProperty;
}
```

**Comment by Koopzington** [comment]
Not sure if the plugin can do anything to prevent that behaviour, but Apache Velocity is actually to blame here: http://people.apache.org/~henning/velocity/html/ch03s04.html

If you want to render $myProperty, you're more or less forced to `#set $myPropery=''` and write  `\$myPropery` in the template.

```php
<?php

declare(strict_types=1);

namespace ${NAMESPACE};

use Psr\Container\ContainerInterface;

final class ${NAME}
{
    #set($container='')
    public function __invoke(ContainerInterface \$container): ${NAME}
    {
        return new ${NAME}();
    }
}
```

**Comment by shift-keshav-pudaruth** [comment]
@Koopzington 

Thanks for your insight!

```php
#set($property='')
public \$property
```

The above works as intended

```php
#set($this='')
\$this->property
```

The above fails to remove the backslash.

Any solutions?

**Comment by Koopzington** [comment]
Just found the following alternative (dirty) approach on [Stackoverflow](https://stackoverflow.com/questions/15547671/escaping-the-dollar-sign-in-velocity-using-backslash-not-working) which also works for that case:
```php
#set($d='$')
${d}this->property;

// Result:
$this->property;
```

**Comment by shift-keshav-pudaruth** [comment]
@Koopzington This solves all of my issues with the templates.

You are my savior.

Issue can be closed now.
